[[Solana]]
ChainID = 'mainnet'
BalancePollPeriod = '8s'
OCR2CachePollPeriod = '1h7m0s'
OCR2CacheTTL = '42m10s'
TxTimeout = '1s'
TxConfirmTimeout = '1h0m0s'
ConfirmPollPeriod = '5m9s'
SkipPreflight = true
Commitment = 'foobar'
MaxRetries = 7

[[Solana.Nodes]]
Name = 'mainnet'
URL = 'http://foo.bar'

[[Solana.Nodes]]
Name = 'mainnet-2'
URL = 'http://fake.url'

[[Solana]]
ChainID = 'testnet'
Enabled = false
SkipPreflight = false

[[Solana.Nodes]]
Name = 'testnet'
URL = 'http://test.sol'
